name: calculator_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.2+6

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^6.2.0
  firebase_core: ^0.5.2+1
  firebase_crashlytics: ^0.2.3+1
  flutter_riverpod: ^0.12.2
  intl: ^0.16.1
  math_expressions: ^2.0.1
  package_info: ">=0.4.3+2<2.0.0"
  shared_preferences: ">=0.5.12+4<2.0.0"
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  image_path_android: "assets/icon/icon_512.png"
  image_path_ios: "assets/icon/icon_512_iphone.png"
  adaptive_icon_foreground: "assets/icon/icon_432_foreground.png"
  adaptive_icon_background: "assets/icon/icon_432_background.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - "assets/icon/icon_512_iphone.png"
